wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712861519.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
task_configs:
  desc: null
  value:
    gsm8k:
      task: gsm8k
      group:
      - math_word_problems
      dataset_path: gsm8k
      dataset_name: main
      training_split: train
      test_split: test
      fewshot_split: train
      doc_to_text: 'Question: {{question}}

        Answer:'
      doc_to_target: '{{answer}}'
      description: ''
      target_delimiter: ' '
      fewshot_delimiter: '


        '
      num_fewshot: 0
      metric_list:
      - metric: exact_match
        aggregation: mean
        higher_is_better: true
        ignore_case: true
        ignore_punctuation: false
        regexes_to_ignore:
        - ','
        - \$
        - '(?s).*#### '
        - \.$
      output_type: generate_until
      generation_kwargs:
        until:
        - 'Question:'
        - </s>
        - <|im_end|>
        do_sample: false
        temperature: 0.0
      repeats: 1
      filter_list:
      - name: strict-match
        filter:
        - function: regex
          regex_pattern: '#### (\-?[0-9\.\,]+)'
        - function: take_first
      - name: flexible-extract
        filter:
        - function: regex
          group_select: -1
          regex_pattern: (-?[$0-9.,]{2,})|(-?[0-9]+)
        - function: take_first
      should_decontaminate: false
      metadata:
        version: 3.0
cli_configs:
  desc: null
  value: {}
