wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712942983.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: infer_eval_step
      6:
      - 3
task_configs:
  desc: null
  value: {}
cli_configs:
  desc: null
  value:
    prefix: ''
    do_sample: true
    temperature: 0.2
    top_k: 0
    top_p: 0.95
    n_samples: 1
    eos: <|endoftext|>
    seed: 0
    model: codeparrot/codeparrot-small
    modeltype: causal
    peft_model: null
    revision: null
    use_auth_token: false
    trust_remote_code: false
    tasks: mbpp
    instruction_tokens: null
    batch_size: 1
    max_length_generation: 512
    precision: fp32
    load_in_8bit: false
    load_in_4bit: false
    left_padding: false
    limit: null
    limit_start: 0
    save_every_k_tasks: -1
    postprocess: true
    allow_code_execution: true
    generation_only: false
    load_generations_path: null
    load_data_path: null
    metric_output_path: evaluation_results.json
    save_generations: true
    load_generations_intermediate_paths: null
    save_generations_path: generations.json
    save_references: true
    save_references_path: references.json
    prompt: prompt
    max_memory_per_gpu: null
    check_references: false
