wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712962335.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 45
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
task_configs:
  desc: null
  value:
    hellaswag:
      task: hellaswag
      group:
      - multiple_choice
      dataset_path: hellaswag
      training_split: train
      validation_split: validation
      process_docs: "def process_docs(dataset: datasets.Dataset) -> datasets.Dataset:\n\
        \    def _process_doc(doc):\n        ctx = doc[\"ctx_a\"] + \" \" + doc[\"\
        ctx_b\"].capitalize()\n        out_doc = {\n            \"query\": preprocess(doc[\"\
        activity_label\"] + \": \" + ctx),\n            \"choices\": [preprocess(ending)\
        \ for ending in doc[\"endings\"]],\n            \"gold\": int(doc[\"label\"\
        ]),\n        }\n        return out_doc\n\n    return dataset.map(_process_doc)\n"
      doc_to_text: '{{query}}'
      doc_to_target: '{{label}}'
      doc_to_choice: choices
      description: ''
      target_delimiter: ' '
      fewshot_delimiter: '


        '
      num_fewshot: 0
      metric_list:
      - metric: acc
        aggregation: mean
        higher_is_better: true
      - metric: acc_norm
        aggregation: mean
        higher_is_better: true
      output_type: multiple_choice
      repeats: 1
      should_decontaminate: false
      metadata:
        version: 1.0
cli_configs:
  desc: null
  value: {}
